checks:
    javascript: true
build:
    environment:
        node: 16.14.2
    nodes:
        analysis:
            tests:
                before:
                    - 'nvm install 16.14.2'
                override:
                    - js-scrutinizer-run
filter:
    excluded_paths:
        - "coverage/" # only relevant on dev
        - "demo/"
        - "node_modules/"
        - "test/"
