name: Publish package

on:
  push:
    tags:
      - '*'

jobs:
  publish-package:
    name: Run yarn publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Publish new version to NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
          registry-url: 'https://registry.npmjs.org'
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  update-docs:
    name: Update documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Generate docs
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
          registry-url: 'https://registry.npmjs.org'
      - run: |
          yarn install
          yarn run generate-docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.GH_TOKEN }}
          repository-name: ArSn/jay-gee-eff-for-web-docs
          branch: master
          folder: docs
