name: Run tests

on: push

jobs:
  run-tests:
    env:
      CC_TEST_REPORTER_ID: e5030292b1e57c0a42df0f32a6f4ac8cc6246340619d54ec60aa3822b6d6fec2
    name: Run tests and report coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.2'

      - name: Setup environment
        run: |
          yarn install
          yarn global add nyc
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Run tests
        run: |
          yarn run test
          yarn run generate-docs

      - name: Report coverage
        run: ./cc-test-reporter after-build
        if: ${{ github.ref == 'refs/heads/master' }}
